import Link from 'next/link';
import './global.scss';
import { Roboto } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({ weight: ['300', '400', '500', '700'], subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/" prefetch={false}>
                  Home
                </Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/blog">Blog</Link>
              </li>
              <li>
                <Link href="/team">Team</Link>
                <ul>
                  <li>
                    <Link href="/dev">dev</Link>
                  </li>
                  <li>
                    <Link href="/market">Marketing</Link>
                  </li>
                </ul>
              </li>
              <li>
                <Link href="/contact">Contact</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
      <footer>
        <p>Ahmed {new Date().getFullYear()}. all rights reserved.</p>
      </footer>
    </html>
  );
}
